config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Instructor routes
  get 'instructors/login', to: 'instructors#login'
  get 'instructor/login/:id', to: 'instructors#login_process'
  post 'instructor/login/:id', to: 'instructors#check'
  post 'instructors/logout', to: 'instructors#logout'
  get 'instructors/signup', to: 'instructors#signup'
  get 'instructors/email', to: 'instructors#email'
  post 'instructors/email', to: 'instructors#emailchecker'
  get 'instructor/:id/edit', to: 'instructors#edit'
  get 'instructor/:id', to: 'instructors#show'
  resources :instructors

  # Student routes
  get 'students/login', to: 'students#login'
  post 'students/logout', to: 'students#logout'
  get 'students/email', to: 'students#email'
  post 'students/email', to: 'students#emailchecker'
  get 'students/signup', to: 'students#signup'
  get 'student/login/:id', to: 'students#login_process'
  post 'student/login/:id', to: 'students#check'
  get 'student/:id/edit', to: 'students#edit'
  get 'student/:id', to: 'students#show'
  resources :students

  # Group routes
  resources :groups

  # Project routes
  resources :projects

  # FeedbackItem routes
  post '/feedback_items', to: 'feedback_items#update'
  get '/feedback_items/:id', to: 'feedback_items#show', as: :feedback_item

  # Evaluations routes
  get '/evaluations/:group/:project', to: 'evaluations#landing', as: :begin_eval
  get '/evaluations/:group/:project/done', to: 'evaluations#done', as: :done_eval
  get '/evaluations/:group/:project/:member', to: 'evaluations#single', as: :continue_eval

  # Application routes
  root 'application#root'
  get '/login', to: 'application#login'

  # Handle test reset, to make testing the app on Heroku possible
  get '/full-system-reset-for-testing-only', to: 'application#full_reset'
  post '/full-system-reset-for-testing-only', to: 'application#do_full_reset'
end

app/models/student.rb
class Student < ApplicationRecord
    has_secure_password

    has_and_belongs_to_many :groups
    
    has_many :feedback_items, dependent: :destroy, foreign_key: :target_id, inverse_of: :target
    has_many :authored_fb_items, class_name: :FeedbackItem, dependent: :nullify, foreign_key: :author_id, inverse_of: :author

    validates :name, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

    VALID_PASSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\W]).{8,}\z/
    validates :password, presence: true, length: {minimum: 8}, format: { with: VALID_PASSWORD_REGEX, message: "must contain at least a lowercase and an uppercase letter, a digit, and a special char" }

    def feedback_for(proj, group)
        self.feedback_items.where(project: proj).filter{ |f| f.author.nil? or group.students.include? f.author }
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy login_process check ]

  def login
    #redirect to email to check email
    return redirect_to students_email_url
  end

  def login_process
    #only for view
  end

  def check
    #the login check process for student
    if @student.authenticate(params[:password])
      log_in_student(@student)
      return redirect_to student_url(id: @student)
    else 
      flash.now[:danger] = "Wrong password!"
      render "login_process"
    end
  end

  def logout
    #logout the current student
    log_out!
    return redirect_to login_url
  end

  def email
    #only for view
  end

  def signup
    #redirect to email to check email
    return redirect_to students_email_url
  end

  def emailchecker
    #check whether the email is registered by instructor.
    @student_email = params[:email].downcase
    @student = Student.find_by(email: @student_email)
    if !@student
        flash[:danger] = "This email is not registered. Use another one."
        return redirect_to students_email_url
    else
      #if yes, then redirect to signup or login based on wether it is signed
      if @student.signed
          return redirect_to url_for(action: "login_process", id: @student)
      else
          log_in_student @student
          return redirect_to edit_student_url(id: @student)
      end
    end
  end

  # GET /students or /students.json
  def index
    #if not login then login
    if not logged_in?
      redirect_to login_url
      return
    end
    #if not instructor login then redirect to student file
    if student_logged_in?
      redirect_to student_url(current_student)
      return
    end
    #Alphabetic sort
    @students = Student.all
    @students = @students.sort
  end

  # GET /students/1 or /students/1.json
  def show
    #check the ID information to allow show
    if not inst_logged_in? and not student_logged_in? @student
      redirect_to login_url
      return
    end
  end

  # GET /students/new
  def new
    #restrict this function only to instructor
    if not inst_logged_in?
      redirect_to instructors_email_url
      return
    end
    #create student
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    #redirect to edit view depends on who is logging in and whether the student is signed up.
    if not inst_logged_in? and not student_logged_in? @student
      redirect_to login_url
      return
    end
    @mode = "editing"
    if !@student.signed
      @mode = "signup"
    end
  end

  # POST /students or /students.json
  def create
    #create a student and record the email as lowercase
    @student = Student.new(student_params)
    @student.email = @student.email.downcase
    if @student.save
      flash[:success] = "Student was successfully created."
      return redirect_to student_url(id: @student)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    #regular update
    if @student.update(student_params)
      flash[:success] = "All set!"
      return redirect_to student_url(@student)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    #before destroy the student, log him out
    log_out! if student_logged_in? @student
    @student.destroy
    flash[:success] = "Student was successfully destroyed."
    return redirect_to students_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:signed, :name, :password, :email)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h4>
      <ul class="mb-0">
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%if !student.signed && student_logged_in? %>
    <input type=hidden name=student[signed] value=true>
  <%end%>

  <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, disabled: !inst_logged_in?, class: "form-control" %>
  </div>

  <div class="form-group">
    <%if inst_logged_in? %>
      <input type=hidden name=student[password] value=DefaultPass3901+>
      <input type=hidden name=student[signed] value=false>
      <% if student.signed %>
        <p class="form-text text-warning">By editing this student's information,
        you will also reset their password & deactivate their account. This student
        will be prompted to create a new password and re-activate their account
        the next time they log in</p>
      <% end %>
    <%elsif !inst_logged_in?%>
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    <%end%>
  </div>

  <div>
    <%if inst_logged_in? and not @student.signed %>
      <%= form.submit "Set Up", class: "btn btn-primary" %>
    <%elsif @mode == "signup"%>
      <%= form.submit "Activate Account", class: "btn btn-primary" %>
    <% elsif inst_logged_in? %>
      <%= form.submit "Save changes and deactivate account", class: "btn btn-danger" %>
    <%else%>
      <%= form.submit "Save changes", class: "btn btn-primary" %>
    <%end%>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="card">
  <h5 class="card-header">
    <% if @mode != "signup" %>
      Edit Student Information
    <% elsif student_logged_in? %>
      Activate Your Account
    <% else %>
      Edit Account Information for Student Sign-Up
    <% end %>
  </h5>
  <div class="card-body">
    <% if @mode == "signup" and student_logged_in? %>
      <p class="card-text">Your account is not activated yet. Please activate your account</p>
      <p class="card-text">Please verify that the name below is yours. Contact the instructors for questions or to update your name.</p>
    <% end %>
    <%= render 'form', student: @student, ins_mode: params[:mode], sign_mode: @mode %>
  </div>
</div>

app/views/students/email.html.erb
<div class="card mx-auto" style="max-width: 25rem">
  <h5 class="card-header">Student Login</h5>
  <div class="card-body">
    <%= form_with url: students_email_url, local: true, method: :post do %>
        <div class="form-group">
            <%= label_tag :email %>
            <%= email_field_tag :email, nil, class: "form-control" %>
        </div>
        <%= link_to "Back", login_path, class: "btn btn-secondary" %>
        <button type="submit" class="btn btn-primary float-right">Next</button>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<div class="mb-2">
  <h1 class="d-inline">Students</h1>
  <%= link_to 'Add', new_student_path, class: "btn btn-primary float-right" %>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Account Activated</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @students.empty? %>
      <tr>
        <td colspan=4>No students yet! Press "Add" to make one</td>
      </tr>
    <% end %>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.signed ? "Yes" : "No" %></td>
        <td>
          <%= link_to 'Show', student %><br>
          <%= link_to 'Edit', edit_student_path(id: student) %><br>
          <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/login_process.html.erb
<div class="card mx-auto" style="max-width: 25rem">
  <h5 class="card-header">Student Login</h5>
  <div class="card-body">
    <%= form_with url: url_for(action: "login_process", id: @student), local: true, method: :post do %>
        <div class="form-group">
            <%= label_tag :password %>
            <%= password_field_tag :password, nil, class: "form-control" %>
        </div>
        <%= link_to "Back", students_email_path, class: "btn btn-secondary" %>
        <button type="submit" class="btn btn-primary float-right">Sign In</button>
    <% end %>
  </div>
</div>

app/views/students/new.html.erb
<div class="card">
  <h5 class="card-header">Create student account</h5>
  <div class="card-body">
    <%= render 'form', student: @student %>
  </div>
</div>

app/views/students/show.html.erb
<div class="card">
  <h5 class="card-header"><%= @student.name %></h5>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Email:</strong>
      <%= @student.email %>
    </li>
    <% if inst_logged_in? %>
      <li class="list-group-item">
        <strong>Account Activated:</strong>
        <%= @student.signed ? "Yes" : "No" %>
      </li>
    <% end %>
  </ul>
  <div class="card-body">
    <%= link_to 'Edit', edit_student_path(id: @student), class: "btn btn-primary" %>
    <% if student_logged_in? @student %>
      <%= link_to 'Logout', students_logout_path, method: :post, data: { confirm: 'Do you want to logout?' }, class: "btn btn-danger" %>
    <% else %>
        <%= link_to 'Delete', @student, method: :delete, data: {confirm: 'Do you really want to delete this student?' }, class: "btn btn-danger"%>
    <%end%>
  </div>
</div>

<%if student_logged_in? @student %>
  <h4 class="mt-5">Open Evaluations:</h4>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Project</th>
        <th>Group</th>
        <th>Completed</th>
        <th>Link</th>
      </tr>
    </thead>

    <tbody>
      <% if @student.groups.empty? %>
        <tr>
          <td colspan=4>You haven't been assigned to any groups yet. Check back later</td>
        </tr>
      <% elsif Project.where(is_open: true).empty? %>
        <tr>
          <td colspan=4>Currently, there are no open projects. Check back later</td>
        </tr>
      <% end %>
      <% @student.groups.each do |g| %>
        <% Project.all.each do |p| %>
          <% next unless p.is_open %>
          <% completed = g.feedback_for(p).where(author: @student).length == (g.students.length - 1) %>
          <tr>
            <td><%= p.name %></td>
            <td><%= g.name %></td>
            <td><%= completed ? "Yes" : "No" %></td>
            <td><%= link_to (completed ? "Edit" : "Complete"), begin_eval_path(group: g, project: p) %></td>
          </tr>
        <%end%>
      <%end%>
    </tbody>
  </table>

<%else%>
  <h4 class="mt-5">Recent Evaluations:</h4>
  <div class="list-group">
    <% if @student.feedback_items.empty? %>
      <li class="list-group-item disabled" aria-disabled="true">
        Nobody has evaluated <%= @student.name %>
      </li>
    <% end %>
    <% @student.feedback_items.each do |f| %>
      <%= link_to "#{f.project.name} (by #{f.author&.name || "Deleted Student"})", f, class: "list-group-item list-group-item-action" %>
    <% end %>
  </div>
    
    
      
    
  </ul>

<%end%>