config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Instructor routes
  get 'instructors/login', to: 'instructors#login'
  get 'instructor/login/:id', to: 'instructors#login_process'
  post 'instructor/login/:id', to: 'instructors#check'
  post 'instructors/logout', to: 'instructors#logout'
  get 'instructors/signup', to: 'instructors#signup'
  get 'instructors/email', to: 'instructors#email'
  post 'instructors/email', to: 'instructors#emailchecker'
  get 'instructor/:id/edit', to: 'instructors#edit'
  get 'instructor/:id', to: 'instructors#show'
  resources :instructors

  # Student routes
  get 'students/login', to: 'students#login'
  post 'students/logout', to: 'students#logout'
  get 'students/email', to: 'students#email'
  post 'students/email', to: 'students#emailchecker'
  get 'students/signup', to: 'students#signup'
  get 'student/login/:id', to: 'students#login_process'
  post 'student/login/:id', to: 'students#check'
  get 'student/:id/edit', to: 'students#edit'
  get 'student/:id', to: 'students#show'
  resources :students

  # Group routes
  resources :groups

  # Project routes
  resources :projects

  # FeedbackItem routes
  post '/feedback_items', to: 'feedback_items#update'
  get '/feedback_items/:id', to: 'feedback_items#show', as: :feedback_item

  # Evaluations routes
  get '/evaluations/:group/:project', to: 'evaluations#landing', as: :begin_eval
  get '/evaluations/:group/:project/done', to: 'evaluations#done', as: :done_eval
  get '/evaluations/:group/:project/:member', to: 'evaluations#single', as: :continue_eval

  # Application routes
  root 'application#root'
  get '/login', to: 'application#login'

  # Handle test reset, to make testing the app on Heroku possible
  get '/full-system-reset-for-testing-only', to: 'application#full_reset'
  post '/full-system-reset-for-testing-only', to: 'application#do_full_reset'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_secure_password
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_PASSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\W]).{8,}\z/
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    validates :password, presence: true, length: {minimum: 8}, format: { with: VALID_PASSWORD_REGEX, message: 
        "must contain at least a lowercase and an uppercase letter, a digit, and a special char" }
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: %i[ show edit update destroy login_process check]
  before_action :inst_verify, only: %i[ index show edit ]

  def login
    #redirect to email to check email
    return redirect_to instructors_email_url
  end

  def login_process
    #view only
  end

  def check
    if @instructor.authenticate(params[:password])
      #Avoid logging in student & instructor at the same time
      log_in_instructor(@instructor)
      return redirect_to instructor_url(id: @instructor)
    else
      #mention for wrong password
      flash.now[:danger] = "Wrong password!"
      render "login_process"
    end
  end

  def emailchecker
    #check if the email in registered
    @instructor_email = params[:email].downcase
    @instructor = Instructor.find_by(email: @instructor_email)
    #redirect to signup or login based on wether the instructor is signed up
    if !@instructor
        flash[:danger] = "This email is not registered. Use another one."
        return redirect_to instructors_email_url
    else
      return redirect_to url_for(action: "login_process", id: @instructor)
    end
  end

  def logout
    #log out the session
    log_out!
    return redirect_to login_url
  end

  def email
    #only for view
  end

  def signup
    #redirect to email to check email
    redirect_to instructors_email_url
  end

  # GET /instructors or /instructors.json
  def index
    #for index view
    @instructors = Instructor.all
    @instructors = @instructors.sort
  end

  # GET /instructors/1 or /instructors/1.json
  def show
    #only for view
  end

  # GET /instructors/new
  def new
    #allow for instructor register based on whether there is any instructor exist.
    return redirect_to root_path unless Instructor.count.zero? || inst_logged_in?
    @mode = "signup"
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
    #allow for editing
    return redirect_to root_path unless inst_logged_in? @instructor
    @mode = "editing"
  end

  # POST /instructors or /instructors.json
  def create
    #TODO:comments
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      flash[:success] = "Instructor was successfully created."
      if Instructor.count == 1
        log_in_instructor @instructor
        return redirect_to root_path
      else 
        return redirect_to instructor_url(@instructor)
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /instructors/1 or /instructors/1.json
  def update
    #TODO:comments
    if @instructor.update(instructor_params)
      flash[:success] = "All set!"
      redirect_to instructor_url(@instructor)
    else
      @mode = "editing"
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /instructors/1 or /instructors/1.json
  def destroy
    #first logout if not
    log_out! if inst_logged_in? @instructor
    #destroy the instructor from database
    @instructor.destroy
    flash[:success] = "Instructor was successfully destroyed."
    redirect_to instructors_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instructor_params
      params.require(:instructor).permit(:name, :email, :password)
    end

    def inst_verify
      return redirect_to root_path unless inst_logged_in?
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor) do |form| %>
  <% if instructor.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h4>
      <ul class="mb-0">
        <% instructor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%if inst_logged_in? && @mode != "editing" %>
      <%= form.submit "Set up", class: "btn btn-primary"%>
    <%elsif @mode == "signup"%>
      <%= form.submit "Sign up account", class: "btn btn-primary"%>
    <%else%>
      <%= form.submit "Save changes", class: "btn btn-primary"%>
    <%end%>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<div class="card">
  <h5 class="card-header">
    <% if @mode != "signup" %>
      Edit Instructor Information
    <% elsif student_logged_in? %>
      Activate Your Account
    <% else %>
      Edit Account Information for Instructor Sign-Up
    <% end %>
  </h5>
  <div class="card-body">
    <% if @mode == "signup" and student_logged_in? %>
      <p class="card-text">Your account is not activated yet. Please activate your account</p>
      <p class="card-text">Please verify that the name below is yours</p>
    <% end %>
    <%= render 'form', instructor: @instructor, ins_mode: params[:mode], sign_mode: @mode %>
  </div>
</div>

app/views/instructors/email.html.erb
<div class="card mx-auto" style="max-width: 25rem">
  <h5 class="card-header">Instructor Login</h5>
  <div class="card-body">
    <%= form_with url: instructors_email_url, local: true, method: :post do %>
        <div class="form-group">
            <%= label_tag :email %>
            <%= email_field_tag :email, nil, class: "form-control" %>
        </div>
        <%= link_to "Back", login_path, class: "btn btn-secondary" %>
        <button type="submit" class="btn btn-primary float-right">Next</button>
    <% end %>
  </div>
</div>

app/views/instructors/index.html.erb
<div class="mb-2">
  <h1 class="d-inline">Instructors</h1>
  <%= link_to 'Add', new_instructor_path, class: "btn btn-primary float-right" %>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.email %></td>
        <td>
          <%= link_to 'Show', instructor %><br>
          <%if inst_logged_in? instructor%>
            <%= link_to 'Edit', edit_instructor_path(instructor) %><br>
          <%end%>
          <%= link_to 'Delete', instructor, method: :delete, data: { confirm: 'Do you really want to delete this instructor?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instructors/login_process.html.erb
<div class="card mx-auto" style="max-width: 25rem">
  <h5 class="card-header">Instructor Login</h5>
  <div class="card-body">
    <%= form_with url: url_for(action: "login_process", id: @instructor), local: true, method: :post do %>
        <div class="form-group">
            <%= label_tag :password %>
            <%= password_field_tag :password, nil, class: "form-control" %>
        </div>
        <%= link_to "Back", students_email_path, class: "btn btn-secondary" %>
        <button type="submit" class="btn btn-primary float-right">Sign In</button>
    <% end %>
  </div>
</div>

app/views/instructors/new.html.erb
<div class="card">
  <h5 class="card-header">Create Instructor Account</h5>
  <div class="card-body">
    <%= render 'form', instructor: @instructor, ins_mode: "instructor"%>
  </div>
</div>

app/views/instructors/show.html.erb
<div class="card">
  <h5 class="card-header"><%= @instructor.name %></h5>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Email:</strong>
      <%= @instructor.email %>
    </li>
  </ul>
  <div class="card-body">
    <% if inst_logged_in? @instructor %>
      <%= link_to 'Edit', edit_instructor_path(@instructor), class: "btn btn-primary" %>
      <%= link_to 'Logout', instructors_logout_path, method: :post, data: { confirm: 'Do you want to logout?' }, class: "btn btn-danger" %>
    <% else %>
      <%= link_to 'Delete', @instructor, method: :delete, data: {confirm: 'Do you really want to delete this instructor?' }, class: "btn btn-danger"%>
    <% end %>
  </div>
</div>

<% if inst_logged_in? @instructor %>

  <h4 class="mt-5">Actions:</h4>
  <div class="list-group">
    <%= link_to "Manage Students", students_path, class: "list-group-item list-group-item-action" %>
    <%= link_to "Manage Groups", groups_path, class: "list-group-item list-group-item-action" %>
    <%= link_to "Manage Projects", projects_path, class: "list-group-item list-group-item-action" %>
    <%= link_to "Manage Instructor Accounts", instructors_path, class: "list-group-item list-group-item-action" %>
  </div>
<% end %>