config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Instructor routes
  get 'instructors/login', to: 'instructors#login'
  get 'instructor/login/:id', to: 'instructors#login_process'
  post 'instructor/login/:id', to: 'instructors#check'
  post 'instructors/logout', to: 'instructors#logout'
  get 'instructors/signup', to: 'instructors#signup'
  get 'instructors/email', to: 'instructors#email'
  post 'instructors/email', to: 'instructors#emailchecker'
  get 'instructor/:id/edit', to: 'instructors#edit'
  get 'instructor/:id', to: 'instructors#show'
  resources :instructors

  # Student routes
  get 'students/login', to: 'students#login'
  post 'students/logout', to: 'students#logout'
  get 'students/email', to: 'students#email'
  post 'students/email', to: 'students#emailchecker'
  get 'students/signup', to: 'students#signup'
  get 'student/login/:id', to: 'students#login_process'
  post 'student/login/:id', to: 'students#check'
  get 'student/:id/edit', to: 'students#edit'
  get 'student/:id', to: 'students#show'
  resources :students

  # Group routes
  resources :groups

  # Project routes
  resources :projects

  # FeedbackItem routes
  post '/feedback_items', to: 'feedback_items#update'
  get '/feedback_items/:id', to: 'feedback_items#show', as: :feedback_item

  # Evaluations routes
  get '/evaluations/:group/:project', to: 'evaluations#landing', as: :begin_eval
  get '/evaluations/:group/:project/done', to: 'evaluations#done', as: :done_eval
  get '/evaluations/:group/:project/:member', to: 'evaluations#single', as: :continue_eval

  # Application routes
  root 'application#root'
  get '/login', to: 'application#login'

  # Handle test reset, to make testing the app on Heroku possible
  get '/full-system-reset-for-testing-only', to: 'application#full_reset'
  post '/full-system-reset-for-testing-only', to: 'application#do_full_reset'
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }

  def feedback_for(group)
    group.feedback_for(self)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :inst_verify

  # GET /projects or /projects.json
  def index
    #regular index
    @projects = Project.all.sort{|s| s.created_at}
  end

  # GET /projects/1 or /projects/1.json
  def show
    #only for view
  end

  # GET /projects/new
  def new
    #regular new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    #only for view
  end

  # POST /projects or /projects.json
  def create
    #regular create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Project was successfully created." 
      redirect_to project_url(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
      #regular update
      if @project.update(project_params)
        flash[:success] = "Project was successfully updated."
        redirect_to project_url(@project)
      else
        render :edit, status: :unprocessable_entity
      end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    #regular destroy
    Group.all.each { |g| @project.feedback_for(g).destroy_all }
    @project.destroy
    flash[:success] = "Project was successfully destroyed."
    redirect_to projects_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :is_open)
    end

    def inst_verify
      return redirect_to root_path unless inst_logged_in?
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def average_score(list)
        list.inject(0.0) {|result, f| result + f.quality + f.participation + f.disagreements} / list.size
    end
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h4>
      <ul class="mb-0">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <div class="form-check">
      <%= form.check_box :is_open, class: "form-check-input" %>
      <%= form.label :is_open, class: "form-check-label" %>
    </div>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<div class="card">
  <h5 class="card-header">Edit Project</h5>
  <div class="card-body">
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="mb-2">
  <h1 class="d-inline">Projects</h1>
  <%= link_to 'Add', new_project_path, class: "btn btn-primary float-right" %>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @projects.empty? %>
      <tr>
        <td colspan=3>No projects yet! Press "Add" to make one</td>
      </tr>
    <% end %>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.is_open ? "Open" : "Closed" %></td>
        <td>
          <%= link_to 'Show', project %><br>
          <%= link_to 'Edit', edit_project_path(project) %><br>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %><br>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="card">
  <h5 class="card-header">New Project</h5>
  <div class="card-body">
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="card">
  <h5 class="card-header"><%= @project.name %></h5>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Status:</strong>
      <%= @project.is_open ? "Open" : "Closed" %>
    </li>
  </ul>
  <div class="card-body">
    <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary" %>
    <%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
</div>

<% if Group.any? %>
  <h4 class="mt-5">Per-Group Breakdown:</h4>
<% end %>
<% Group.all.each do |g| %>
<div class="card my-3">
  <h5 class="card-header"><%= g.name %></h5>
  <table class="table table-striped table-bordered card-body mb-0">
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Average Score</th>
        <th>Details by Author</th>
      </tr>
    </thead>

    <tbody>
      <% if g.students.empty? %>
        <tr>
          <td colspan=3>This group has no students</td>
        </tr>
      <% end %>
      <% g.students.each do |s|%>
        <tr>
          <td><%= s.name%></td>
          <% fbItems = s.feedback_for(@project,g)%>
          <% if fbItems.empty? %>
            <td>N/A</td>
            <td>N/A</td>
          <% else%>
            <td><%= average_score(fbItems)%>/15</td>
            <td>
              <%= fbItems.map do |f| %>
                <% link_to f.author&.name || "Deleted Student", feedback_item_path(f) %> 
              <% end.join(", ").html_safe %>
            </td>
          <%end%>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<%end%>