config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Instructor routes
  get 'instructors/login', to: 'instructors#login'
  get 'instructor/login/:id', to: 'instructors#login_process'
  post 'instructor/login/:id', to: 'instructors#check'
  post 'instructors/logout', to: 'instructors#logout'
  get 'instructors/signup', to: 'instructors#signup'
  get 'instructors/email', to: 'instructors#email'
  post 'instructors/email', to: 'instructors#emailchecker'
  get 'instructor/:id/edit', to: 'instructors#edit'
  get 'instructor/:id', to: 'instructors#show'
  resources :instructors

  # Student routes
  get 'students/login', to: 'students#login'
  post 'students/logout', to: 'students#logout'
  get 'students/email', to: 'students#email'
  post 'students/email', to: 'students#emailchecker'
  get 'students/signup', to: 'students#signup'
  get 'student/login/:id', to: 'students#login_process'
  post 'student/login/:id', to: 'students#check'
  get 'student/:id/edit', to: 'students#edit'
  get 'student/:id', to: 'students#show'
  resources :students

  # Group routes
  resources :groups

  # Project routes
  resources :projects

  # FeedbackItem routes
  post '/feedback_items', to: 'feedback_items#update'
  get '/feedback_items/:id', to: 'feedback_items#show', as: :feedback_item

  # Evaluations routes
  get '/evaluations/:group/:project', to: 'evaluations#landing', as: :begin_eval
  get '/evaluations/:group/:project/done', to: 'evaluations#done', as: :done_eval
  get '/evaluations/:group/:project/:member', to: 'evaluations#single', as: :continue_eval

  # Application routes
  root 'application#root'
  get '/login', to: 'application#login'

  # Handle test reset, to make testing the app on Heroku possible
  get '/full-system-reset-for-testing-only', to: 'application#full_reset'
  post '/full-system-reset-for-testing-only', to: 'application#do_full_reset'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include LoginHelper

  def root
    # Must be a new instance! There are no instructors. Prompt to make one
    if Instructor.count.zero?
      flash[:info] = "This is a new instance of the Student Evaluation System. Please register an instructor account to get started"
      redirect_to new_instructor_url

    # An instructor is logged in. Redirect to their homepage
    elsif inst_logged_in?
      redirect_to instructor_url(current_inst)

    # A student is logged in. Redirect to their homepage
    elsif student_logged_in?
      redirect_to student_url(current_student)

    # Nobody is logged in. Redirect to the login page
    else
      redirect_to login_url
    end
  end

  def login
    # Redirect to landing page if already logged in
    return redirect_to root_path if logged_in?
  end

  def full_reset
  end

  def do_full_reset
    if params[:key] == '0c90301e-0b89-4840-b42b-0a86d3eef8d4'
      # https://stackoverflow.com/a/69955217
      Rails.application.eager_load! unless Rails.application.config.eager_load

      ApplicationRecord.descendants.count.times do # TOOD: This is a hack
        begin
          ApplicationRecord.descendants.each { |model| model.delete_all }
        rescue
          # Probably some database error happened here due to foregin key relationships
        end
      end

      flash[:success] = "Database dropped!"
      redirect_to root_url
    else
      flash.now[:danger] = 'Incorrect Key!'
      render :full_reset
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Helps construct the navbar
  def nav_item(name, icon, controller, path, method="get")

    # Highlight the active nav item, with special treatment of "home"
    active = (params[:controller] == controller)
    if (inst_logged_in? and (request.fullpath == instructor_path(current_inst))) or
       (student_logged_in? and (request.fullpath == student_path(current_student)))
      active = (controller == "home")
    elsif not logged_in? and (controller == "home")
      active = true
    end
    active = active ? "active" : ""

    child = "<i class=\"fa fa-#{icon}\" aria-hidden=\"true\"></i> #{name}".html_safe
    link_to child, path, class: "nav-item nav-link text-center px-3 #{active}", method: method
  end

end

app/views/application/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-sm navbar-dark mb-3">
  <span class="navbar-brand"></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="navbarContent">
    <div class="navbar-nav mx-auto">

      <%= nav_item "Home", "home", "home", root_path %>

      <% if inst_logged_in? %>
        <%= nav_item "Students", "graduation-cap", "students", students_path %>
        <%= nav_item "Groups", "users", "groups", groups_path %>
        <%= nav_item "Projects", "briefcase", "projects", projects_path %>
        <%= nav_item "Instructors", "user", "instructors", instructors_path %>
        <%= nav_item "Logout", "sign-out", "", instructors_logout_path, method: "post" %>
        
      <% elsif student_logged_in? %>
        <%= nav_item "Logout", "sign-out", "", students_logout_path, method: "post" %>
        
      <% end %>

    </div>
  </div>
</nav>

app/views/application/full_reset.html.erb
<div class="card">
  <h5 class="card-header">Full System Reset (for testing only!!)</h5>
  <div class="card-body">
    <p class="card-text">This will wipe out the database. Please enter the reset key to continue</p>

    <%= form_with url: full_system_reset_for_testing_only_path do |f| %>
      <div class="form-group">
    	  <%= f.label :key %>
    	  <%= f.text_field :key, class: "form-control" %>
    	</div>
    	<%= f.submit "Drop Database", class: "btn btn-danger float-right" %>
    <% end %>
  </div>
</div>

app/views/application/login.html.erb
<div class="jumbotron">
  <h1 class="display-4">Student Evaluation System</h1>
  <p class="lead">Welcome to Group 7's Student Evaluation System! You need to log in to continue...</p>
  <hr class="my-3">
  <p>If you don't have an account, you'll need to ask a course instructor to register one for you. I want to log in as a...</p>
  <div class="lead">
    <%= link_to "Student", students_login_path, class: "btn btn-primary btn-lg" %>
    <%= link_to "Instructor", instructors_login_path, class: "btn btn-primary btn-lg" %> 
  </div>
</div>